name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            runtime: win-x64
          - os: ubuntu-latest
            runtime: linux-x64

    steps:
    - uses: actions/checkout@v5

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish MsixvcPackageDownloader/MsixvcPackageDownloader.csproj -r ${{ matrix.runtime }} --self-contained true -p:PublishSingleFile=true --configuration Release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.runtime }}-build
        path: MsixvcPackageDownloader/bin/Release/net8.0/${{ matrix.runtime }}/publish/*
